<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.zoho.flow.samples</groupId>
    <artifactId>hello-static</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>Zoho Flow Hello Static Sample</name>

    <repositories>
        <repository>
            <id>zohoflow-sdk</id>
            <url>https://maven.zohodl.com/flow</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.zoho.flow</groupId>
            <artifactId>zohoflow-onprem-extension-sdk</artifactId>
            <version>1.0.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <finalName>hello-static</finalName>
                    <archive>
                        <manifestEntries>
                            <Implementation-Title>Zoho Flow Hello Static Sample</Implementation-Title>
                            <Implementation-Version>1.0.0</Implementation-Version>
                            <Implementation-Vendor>Zoho Corporation</Implementation-Vendor>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <descriptors>
                        <descriptor>assembly.xml</descriptor>
                    </descriptors>
                    <finalName>hello-static</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>
                <executions>
                    <execution>
                        <id>make-upload-zip</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
