package com.zoho.flow.samples.hello;

import com.zoho.agent.flow.customclass.CustomClassData;
import com.zoho.agent.flow.customclass.annotation.Description;
import com.zoho.agent.flow.customclass.annotation.Label;

public final class HelloOutput extends CustomClassData {

    @Label("Message")
    @Description("Greeting generated by the connector")
    public String message;

    public HelloOutput() {
    }
}
