package com.zoho.flow.samples.hello;

import com.zoho.agent.flow.extension.ExtensionData;
import com.zoho.agent.flow.extension.annotation.Description;
import com.zoho.agent.flow.extension.annotation.Label;

public final class HelloOutput extends ExtensionData {

    @Label("Message")
    @Description("Greeting generated by the connector")
    public String message;

    public HelloOutput() {
    }
}
